name: Publish to production

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install npm packages
        run: npm install

      - name: Run tests
        run: npm test

      - name: authorization
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: deploy files to production
        run: |
          gsutil -h "Cache-Control:must-revalidate, max-age=5" rsync -R ./pub gs://insights-survey-client
